#! /bin/sh

#~/.screenlayout/1monitor.sh
~/.screenlayout/3monitor.sh
sxhkd &
nitrogen --restore
wal -R
picom --experimental-backend &
~/.config/polybar/launch.sh

# Latte dock here to not break window placement
#latte-dock

bspc monitor HDMI2 -d 4 5 6
bspc monitor eDP1 -d 1 2 3
bspc monitor DP1 -d 7 8 9

bspc monitor HDMI2 -a s tg 

bspc config border_width         4
bspc config pointer_follows_monitor true

bspc config window_gap 30
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color15"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"
bspc config remove_unplugged_monitors true;
bspc config center_pseudo_tiled true;


bspc config external_rules_command ~/.local/bin/bspwm-rules

#bspc rule -a mpv state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Wine state=fullscreen
#bspc rule -a Nitrogen state=floating
#bspc rule -a plasmashell state=floating sticky=on border=off
#bspc rule -a krunner state=floating layer=above sticky=on border=off
#bspc rule -a Plasma state=floating
#bspc rule -a plasma-desktop state=floating
#bspc rule -a Klipper state=floating
#bspc rule -a Kmix state=floating
#bspc rule -a Plasmoidviewer state=floaitng
#bspc rule -a latte-dock monitor=HDMI2 layer=above border=off manage=on state=floating
#bspc rule -a '*:plasma' state=floating
#bspc rule -a '*:plasmashell' state=floating
#bspc rule -a '*:WifiConnect' state=floating rectangle=1000x500
#bspc rule -a '*:BtSetup' state=floating rectangle=500x500
#bspc rule -a '*:Calendar' state=floating rectangle=1000x650
#bspc rule -a Deadd-notification-center state=floating

spotify &
telegram-desktop &
